services:
  ucenter:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - /var/docker/meta-ucenter/config:/app/config
    depends_on:
      - redis
      - nats
    restart: on-failure
  redis:
    image: redis
    ports:
      - '6379:6379'
  nats:
    image: nats
    ports:
      - '4222:4222'
