services:
  ucenter:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - /var/docker/ucenter/config:/app/config
    depends_on:
      - redis
      - nats
    restart: on-failure
  redis:
    image: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6379"]
      interval: 30s
      timeout: 10s
      retries: 5
  nats:
    image: nats
    ports:
      - '4222:4222'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4222"]
      interval: 30s
      timeout: 10s
      retries: 5
