# config.development.yaml
app:
  port: 3000

microservice:
  options:
    transport: 2
    options:
      servers: ['nats://localhost:4222']
  clients:
    network:
      transport: 2 # NATS
      options:
        servers: ['nats://localhost:4222']

db:
  host:
  username:
  password:
  database:

jwt:
  access_token_name:
  refresh_token_name:
  access_token_expires: '20m'
  refresh_token_expires: '30d'
  issuer:
  aud:

cors:
  origins:
    - 'http://127.0.0.1:8000'

cookies:
  access_domain: '127.0.0.1'
  access_path: '/'
  refresh_domain: '127.0.0.1'
  refresh_path: '/accounts/tokens'

sendcloud:
  user:
  key:

redis:
  host: '127.0.0.1'
  port: 6379
  pass:
  vcode_ttl: 600
  vcode_max_items: 100000
