# config.biz.development.yaml
email:
  # currently support ['mailgun', 'sendcloud']
  service: 'mailgun'
  from_name: 'Meta Network Team'
  from_email:

hcaptcha:
  enabled: false
  secret:

dingding_bot:
  enabled: false
  api:

# SocialAuth
github:
  client_id:
  client_secret:

gitee:
  client_id:
  client_secret:

fleek:
  api_key:
  api_secret:

webauthn:
  rp:
    id: 'localhost'
    origin: 'http://localhost:8000'
    name:

spider_platform_allowlist:
  - 'matataki'

invitation:
  new_when_created_user: 3
  new_when_occupied_hex_grids: 3

user:
  get_vcode_times_limit_enabled: true
  get_vcode_times_ttl: 7200
  get_vcode_times_cool_down_time: 300
  get_vcode_times_limit: 5
  try_vcode_attempts_limit: 10
